config/routes.rb
Rails.application.routes.draw do
  get "session/new"
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/help", to: "static_pages#help"
  get "/signup",  to: "users#new"
  post "/signup",  to: "users#create"
  get "/login",  to: "sessions#new"
  post "/login",  to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :cities
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  validates :name, presence: true, length: {maximum: 50}
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, inverse_of: :profiles
  validates :address, presence: true, length: {maximum: 255}
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :profiles, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :profiles, allow_destroy: true, reject_if: :all_blank

  before_save {email.downcase!}
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX}, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find params[:id]
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new city_params
    if @city.save
      flash[:success] = "create success"
      redirect_to @city
    else
      render :new
    end
  end

  private

  def city_params
    params.require(:city).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      login_user user
      redirect_to user
    else
      flash[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i(index edit update destroy)
  before_action :correct_user, only: %i(edit update)
  before_action :admin_user, only: :destroy

  def index
    @users = User.all.page(params[:page]).per(5)
  end

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
    @user.profiles.build
  end

  def create
    @user = User.new user_params
    if @user.save
      login_user @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to users_url
    else
      render :new
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find(params[:id]) 
    if @user.update_attributes user_params 
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find params[:id]
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :gender, :dob, :role, :password, :description,
     :password_confirmation, :city_id, profiles_attributes: [:id, :address, :_destroy])
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please login"
      redirect_to login_url
    end
  end
  
  def correct_user
    @user = User.find params[:id]
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # return the full title on the per-page basics
  def full_title(page_title = "")
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      page_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # logs in the given user
  def login_user(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user || User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # return the gravatar for the given user
  def gravatar_for(user,  size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/cities/new.html.erb
<% provide(:title, "City") %>
<h1>Create city</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@city) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control"%>

      <%= f.submit "Create", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/cities/show.html.erb
<% provide(:title, "City")%>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render "layouts/rails_default" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render "layouts/flash" %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development?%>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contails <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
    Tutorial</em></a> is a
  <a href="https://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
    to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
    This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
    <a href="https://www.railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
    <a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em> book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home")%>
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("dog.jpg", alt: "dog logo"),
  'http://rubyonrails.org/' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/error_messages", object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :dob %>
  <div class="input-group date" id="datetimepicker">
    <%= f.text_field :dob, placeholder: "Select the date and time", class: "form-control" %>
    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
  </div></br>

  <div class="row">
    <div class="col-md-2">
      <%= f.label :gender %>
    </div>
    <div class="col-md-5">
      <div class="form-group">
        <div class="col-md-3">
          <%= f.radio_button :gender, false, :checked => true %>
        </div>
        <div class="col-md-9">
          <%= f.label :gender, "Male", value: 1 %></br>
        </div>
      </div>
    </div>
    <div class="col-md-5">
      <div class="form-group">
        <div class="col-md-3">
          <%= f.radio_button :gender, true %>
        </div>
        <div class="col-md-9">
          <%= f.label :gender, "Female", value: 0  %>
        </div>
      </div>
    </div>
  </div></br>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <div class="row">
    <div class="col-md-2">
      <%= f.label :role %>
    </div>
    <div class="col-md-10">
      <div class="form-group">
        <div class="col-md-1">
          <%= f.check_box :role, {}, true %>
        </div>
        <div class="col-md-11">
          <%= f.label :role, "Admin"%></br>
        </div>
      </div>
    </div>
  </div></br>

  <%= f.label :description %>
  <%= f.text_area :description, cols: 2, rows: 6 %>

  <%= f.label :city_id %>
  <%= f.select :city_id, City.all.collect {|c| [c.name, c.id]},
    {include_blank: true}, class: "form-control" %>

  <%= f.fields_for :profiles do |profile| %>
    <%= render "profile_fields", f: profile %>
  <% end %>

  <div class="links">
    <%= link_to_add_association "Add address", f, :profiles, class: "btn btn-primary" %>
  </div></br>

  <%= f.submit "create", class: "btn btn-primary" %>
<% end %>

app/views/users/_profile_fields.html.erb
<div class="nested-fields">
  <%= f.label :address %>
  <%= f.text_field :address, class: "form-control" %>
  <%= link_to_remove_association "remove address", f, class: "btn btn-danger" %>
</div></br>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= paginate @users, theme: "twitter-bootstrap-3"  %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>
<%= paginate @users, theme: "twitter-bootstrap-3"  %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>